### ISSUE TITLE
Roadmap of AstroNbodySim.jl

### ISSUE THREAD

**Issue by islent** [JuliaAstroSim/AstroNbodySim.jl#5]
Hello everyone, this issue tracks new features and bug fixes of `AstroNbodySim`.

The automatic TODO list is maintained at https://github.com/orgs/JuliaAstroSim/projects/4

## New features
- [ ] AMR Poisson solver
- [ ] MOdified Newtonian Dynamics (MOND)
- [ ] Initial conditions
  - [ ] Spiral galaxy
  - [ ] Disk galaxy
  - [ ] Dark matter halos
- [ ] Octree
  - [ ] Neighbour searching
  - [ ] Iterators
  - [ ] Support Float32
- [ ] I/O
  - [ ] support HDF5
- [ ] Parallelism
  - [ ] Tiled GPU computing

## Bug fixes
- [ ] support individual smoothing lengths https://github.com/JuliaAstroSim/AstroNbodySim.jl/issues/4

**Comment by glanzkaiser** [comment]
On the galaxies collision, can the other galaxy has different color of the planets in that galaxy?

**Comment by islent** [comment]
I don't fully understand your question @glanzkaiser .

Stars from different galaxies can be distinguished by particle ID.

Besides, here is not a good place to discuss usage questions. Please open a new issue.
